### ISSUE TITLE
Laporan

### ISSUE THREAD

**Issue by nisahanum** [ChampionsFutsalLeagueCiwaruga/DinanSagaraBackend#1]
Coba upload laporan bab 1-2 nya ya

**Comment by dsagara** [comment]
[BAB 1.docx](https://github.com/ChampionsFutsalLeagueCiwaruga/DinanSagaraBackend/files/568142/BAB.1.docx)
[BAB 2.docx](https://github.com/ChampionsFutsalLeagueCiwaruga/DinanSagaraBackend/files/568143/BAB.2.docx)

Berikut Lampirannya
